#常駐的docker container執行
version: '3.7'  
services:   
  mongo:    
    container_name: mongo
    image: mongo:latest
    volumes:
      - C:\mongodb\db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alles
      - MONGO_INITDB_ROOT_PASSWORD=1212
    command: mongod --auth
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '1024m'
    ports:
      - "27017:27017"
    restart: always